export const clerkAuthAppearance = {
  options: {
    logoImageUrl:
      "https://res.cloudinary.com/revrebel/image/upload/v1761516148/RR/Logos/revrebel-logo.png",
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    elevation: "raised" as const,
  },
  variables: {
    colorPrimary: "#163666",
    colorPrimaryForeground: "#eff5f6",
    colorForeground: "#163666",
    colorMutedForeground: "#536782",
    colorBackground: "#eff5f6",
    colorInput: "#ffffff",
    colorInputForeground: "#163666",
    colorNeutral: "#163666",
    colorBorder: "#163666",
    colorRing: "#163666",
    colorDanger: "#e05047",
    colorSuccess: "#71c9c5",
    colorWarning: "#faca78",
    borderRadius: "0.175rem",
    spacing: "1rem",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontFamilyButtons: "Khand, 'Arial Narrow', sans-serif",
  },
  elements: {
    rootBox: {
      width: "100%",
      maxWidth: "480px",
    },
    cardBox: {
      width: "100%",
      maxWidth: "480px",
      overflow: "hidden",
      backgroundColor: "var(--clerk-color-background)",
      border: "3px solid var(--clerk-color-ring)",
      borderRadius: "0.55rem",
      boxShadow: "0 8px 20px rgba(0, 0, 0, 0.06)",
    },
    card: {
      backgroundColor: "var(--clerk-color-background)",
      border: "0",
      borderRadius: "0",
      boxShadow: "none",
    },
    logoBox: {
      marginBottom: "1.35rem",
    },
    logoImage: {
      width: "190px",
      maxWidth: "72%",
      height: "auto",
    },
    header: {
      paddingTop: "0.25rem",
    },
    headerTitle: {
      color: "#163666",
      fontFamily: "Khand, 'Arial Narrow', sans-serif",
      fontSize: "1.9rem",
      fontWeight: 700,
      lineHeight: 1,
      letterSpacing: "-0.015em",
      textTransform: "uppercase" as const,
    },
    headerSubtitle: {
      maxWidth: "340px",
      marginInline: "auto",
      color: "#536782",
      fontSize: "0.9rem",
      fontWeight: 500,
      lineHeight: 1.45,
      letterSpacing: "0.025em",
    },
    socialButtonsBlockButton: {
      minHeight: "42px",
      backgroundColor: "#ffffff",
      color: "#163666",
      border: "1px solid rgba(22, 54, 102, 0.32)",
      borderRadius: "0.175rem",
      boxShadow: "none",
      fontWeight: 500,
    },
    dividerLine: {
      backgroundColor: "rgba(22, 54, 102, 0.16)",
    },
    dividerText: {
      color: "#536782",
      fontSize: "0.82rem",
    },
    formFieldLabel: {
      color: "#163666",
      fontSize: "0.82rem",
      fontWeight: 600,
    },
    formFieldInput: {
      minHeight: "44px",
      backgroundColor: "#ffffff",
      color: "#163666",
      border: "1px solid #163666",
      borderRadius: "0.175rem",
      boxShadow: "none",
      fontSize: "0.9rem",
      "&:focus": {
        borderColor: "#163666",
        boxShadow: "0 0 0 2px rgba(22, 54, 102, 0.12)",
      },
    },
    formButtonPrimary: {
      minHeight: "58px",
      backgroundColor: "#163666",
      color: "#eff5f6",
      borderRadius: "0.175rem",
      boxShadow: "none",
      fontFamily: "Khand, 'Arial Narrow', sans-serif",
      fontSize: "1.08rem",
      fontWeight: 700,
      letterSpacing: "0.02em",
      textTransform: "uppercase" as const,
      "&:hover, &:focus, &:active": {
        backgroundColor: "#0d274e",
      },
    },
    footer: {
      backgroundColor: "rgba(22, 54, 102, 0.035)",
      borderTop: "1px solid #163666",
    },
    footerAction: {
      paddingBlock: "1rem",
      borderBottom: "1px solid rgba(22, 54, 102, 0.42)",
    },
    footerActionText: {
      color: "#536782",
      fontSize: "0.82rem",
    },
    footerActionLink: {
      color: "#163666",
      fontFamily: "Khand, 'Arial Narrow', sans-serif",
      fontSize: "0.9rem",
      fontWeight: 700,
      letterSpacing: "0.025em",
      textTransform: "uppercase" as const,
    },
    footerPages: {
      paddingBlock: "0.85rem",
      color: "#536782",
    },
  },
};
